apiVersion: v2
name: coroot
description: A monitoring and troubleshooting tool for microservice architectures.
type: application
version: 0.8.7
appVersion: "0.29.1"
dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 15.16.*
    condition: prometheus.enabled
  - name: node-agent
    version: 0.1.55
    repository: https://coroot.github.io/helm-charts
    condition: node-agent.enabled
  - name: clickhouse
    version: 3.1.*
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
  - name: opentelemetry-collector
    version: 0.52.*
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
