apiVersion: v2
name: coroot
description: A monitoring and troubleshooting tool for microservice architectures.
type: application
version: 0.2.23
appVersion: "0.16.2"
dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 15.16.*
    condition: prometheus.enabled
  - name: node-agent
    version: 0.1.24
    repository: https://coroot.github.io/helm-charts
    condition: node-agent.enabled
  - name: pyroscope
    repository: https://pyroscope-io.github.io/helm-chart
    version: 0.2.*
    condition: pyroscope.enabled
  - name: pyroscope-ebpf
    repository: https://pyroscope-io.github.io/helm-chart
    version: 0.1.*
    condition: pyroscope-ebpf.enabled
  - name: clickhouse
    version: 3.1.*
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
  - name: opentelemetry-collector
    version: 0.52.*
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled