aws:
  region: ""
  key: ""
  secret: ""

rds:
  user: ""
  password: ""
  filter: ""

ec:
  filter: ""

serviceAccountName: ""

replicaCount: 1

image:
  repository: ghcr.io/coroot/coroot-aws-agent
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podMonitor: false
