{{- if .Values.corootCE.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coroot.fullname" . }}
  labels:
    {{- include "coroot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.corootCE.service.type }}
  ports:
    - port: {{ .Values.corootCE.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "coroot.selectorLabels" . | nindent 4 }}
{{- end -}}
